ALTER TYPE "BannerType" ADD VALUE IF NOT EXISTS 'HERO';
ALTER TYPE "BannerType" ADD VALUE IF NOT EXISTS 'LOOKBOOK';
ALTER TYPE "BannerType" ADD VALUE IF NOT EXISTS 'CERTIFICATE';
ALTER TYPE "BannerType" ADD VALUE IF NOT EXISTS 'BRAND';

ALTER TABLE "Order" ADD COLUMN IF NOT EXISTS "customerName" TEXT;
ALTER TABLE "Order" ADD COLUMN IF NOT EXISTS "phone" TEXT;
ALTER TABLE "Order" ADD COLUMN IF NOT EXISTS "email" TEXT;
ALTER TABLE "Order" ADD COLUMN IF NOT EXISTS "deliveryType" TEXT;
ALTER TABLE "Order" ADD COLUMN IF NOT EXISTS "paymentType" TEXT;
ALTER TABLE "Order" ADD COLUMN IF NOT EXISTS "address" TEXT;
ALTER TABLE "Order" ADD COLUMN IF NOT EXISTS "comment" TEXT;
ALTER TABLE "Order" ADD COLUMN IF NOT EXISTS "company" TEXT;
ALTER TABLE "Order" ADD COLUMN IF NOT EXISTS "inn" TEXT;
